import Head from "next/head";
import Display from "./components/display";
import Message from "./components/messages";
import { PrismaClient } from "@prisma/client";
import { useState } from "react";
const prisma = new PrismaClient();

export async function getServerSideProps() {
  const messagesData = await prisma.messages.findMany();
  const messages = JSON.parse(JSON.stringify(messagesData)); // suspicious stringifying: see [https://github.com/vercel/next.js/issues/11993]
  return {
    props: {
      initialMessages: messages
    },
  };
}



export default function Home({initialMessages }) {
  const [messageState, setMessageState] = useState(initialMessages);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" flex justify-center">
          <div className=" mt-9">
          <Display propUsers={messageState} />
          <div className="mt-9">
          <Message />
          </div>
          </div>
        </div>
      </main>
    </>
  );
}
